### ISSUE TITLE
离线部署 ansible-playbook bootstrap.yml 时遇到错误 ：check_system_static：ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2

### ISSUE THREAD

**Issue by b0r0j0** [pingcap/tidb-tools#136]
离线部署 ansible-playbook bootstrap.yml 到check_system_static 时遇到错误 ：

`TASK [check_system_static : get facts] *****************************************************************************************
2018-11-29 13:55:29,879 p=28716 u=tidb |  ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2
2018-11-29 13:55:29,880 p=28716 u=tidb |  to see the full traceback, use -vvv
2018-11-29 13:55:29,882 p=28716 u=tidb |  the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 292, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 315, in run
    results += self._process_pending_results(iterator, max_passes=max(1, int(len(self._tqm._workers) * 0.1)))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 117, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 606, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, result_item['ansible_facts'].copy())
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 597, in set_host_facts
    self._fact_cache.update(host.name, facts)
TypeError: update expected at most 1 arguments, got 2`

**Comment by WangXiangUSTC** [comment]
@liubo0127  PTAL

**Comment by IANTHEREAL** [comment]
@b0r0j0 I think it's better to create an issue in https://github.com/pingcap/tidb-ansible
