### ISSUE TITLE
remove-columns cause index lookup error

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tidb-tools#234]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

run sync_diff in sharding mode, remove-columns option changes the columns in table info slice, while index column keeps the table offset, which leads to index out of range error

```
[[check-tables]]
schema = "db_target"
tables = ["t_target"]

[[table-config]]
schema = "db_target"
table = "t_target"
remove-columns = ["id"]
is-sharding = true
index-fields = "uid"

[[table-config.source-tables]]
instance-id = "source-1"
schema = "sharding1"
table  = "~t.*"

[[table-config.source-tables]]
instance-id = "source-2"
schema = "sharding1"
table  = "~t.*"
```

```
mysql> show create table t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` int(11) DEFAULT NULL,
  `name` varchar(80) DEFAULT NULL,
  `info` varchar(100) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `info_json` json GENERATED ALWAYS AS (`info`) VIRTUAL,
  `id_gen` int(11) GENERATED ALWAYS AS ((`uid` + 1)) VIRTUAL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uid` (`uid`),
  UNIQUE KEY `id_gen` (`id_gen`),
  KEY `multi_col_idx` (`uid`,`id_gen`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)
```

2. What did you expect to see?

diff runs successfully

3. What did you see instead?

```
panic: runtime error: index out of range

goroutine 42 [running]:
github.com/pingcap/tidb-tools/pkg/dbutil.SelectUniqueOrderKey(0xc0003ba500, 0x0, 0x20, 0x203000, 0x203000, 0x0, 0x0)
        /home/apple/work/code/pingcap/gopath/src/github.com/pingcap/tidb-tools/pkg/dbutil/index.go:183 +0xb3b
github.com/pingcap/tidb-tools/pkg/diff.getChunkRows(0x1240ac0, 0xc0000b8010, 0xc00023c3c0, 0xc0002d1b50, 0x9, 0xc00031d19a, 0x2, 0xc0003ba500, 0xc00031dda0, 0xf, ...)
        /home/apple/work/code/pingcap/gopath/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:766 +0x76
github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).compareRows(0xc000238620, 0x1240ac0, 0xc0000b8010, 0xc0003b8af0, 0x3, 0x16, 0x0)
        /home/apple/work/code/pingcap/gopath/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:456 +0x224
github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual(0xc000238620, 0x1240ac0, 0xc0000b8010, 0x0, 0xc0003b8af0, 0x0, 0x0, 0x0)
        /home/apple/work/code/pingcap/gopath/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:421 +0x51a
github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunksDataEqual(0xc000238620, 0x1240ac0, 0xc0000b8010, 0x0, 0xc000390f60, 0xc000090700)
        /home/apple/work/code/pingcap/gopath/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:351 +0x17b
created by github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).CheckTableData
        /home/apple/work/code/pingcap/gopath/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:239 +0x21b
```
6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

```
➜  ./bin/sync_diff_inspector -V
version:
sync_diff_inspector: v1.0.0~rc2+git.661b5b4
Git Commit Hash: 661b5b4ff0d07f0cbf126a9d59a82e610ee84d12
UTC Build Time: 2019-04-23 08:03:21
Go Version: go1.11.2
```

**Comment by WangXiangUSTC** [comment]
fix in #242
