### ISSUE TITLE
diff: get send on closed channel panic when cancel

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/tidb-tools#375]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

cancel diff when running

2. What did you expect to see?

can exit success

3. What did you see instead?

`[2020/06/30 06:37:04.116 +00:00] [INFO] [diff.go:464] ["checksum is equal"] [table=`pocket`.`dvndnej`] [where="(TRUE AND TRUE)"] [args=null] [checksum=0]
[2020/06/30 06:37:04.119 +00:00] [ERROR] [checkpoint.go:71] ["save chunk info failed"] [error="context deadline exceeded"] [errorVerbose="context deadline exceeded\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15\ngithub.com/pingcap/tidb-tools/pkg/dbutil.ExecSQLWithRetry\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/dbutil/common.go:663\ngithub.com/pingcap/tidb-tools/pkg/diff.saveChunk\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/checkpoint.go:69\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual.func1\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:395\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual.func2\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:411\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:433\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunksDataEqual\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:374\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/global.go:42\ngithub.com/pingcap/tidb-tools/pkg/diff.saveChunk\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/checkpoint.go:71\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual.func1\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:395\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual.func2\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:411\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:433\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunksDataEqual\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:374"]
[2020/06/30 06:37:04.119 +00:00] [WARN] [diff.go:661] ["save table summary info failed"] [schema=pocket] [table=dvndnej] [error="context deadline exceeded"] [errorVerbose="context deadline exceeded\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15\ngithub.com/pingcap/tidb-tools/pkg/diff.getChunkSummary\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/checkpoint.go:175\ngithub.com/pingcap/tidb-tools/pkg/diff.updateTableSummary\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/checkpoint.go:227\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).UpdateSummaryInfo.func1.1\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:659\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).UpdateSummaryInfo.func1.2\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:665\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).UpdateSummaryInfo.func1\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:675\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"]
[2020/06/30 06:37:04.119 +00:00] [WARN] [diff.go:397] ["update chunk info"] [error="context deadline exceeded"] [errorVerbose="context deadline exceeded\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15\ngithub.com/pingcap/tidb-tools/pkg/dbutil.ExecSQLWithRetry\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/dbutil/common.go:663\ngithub.com/pingcap/tidb-tools/pkg/diff.saveChunk\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/checkpoint.go:69\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual.func1\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:395\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual.func2\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:411\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:433\ngithub.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunksDataEqual\n\t/go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:374\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"]
panic: send on closed channel

goroutine 47673361 [running]:
github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunksDataEqual(0xc0009d1d40, 0x2dcc360, 0xc000946180, 0x2945400, 0xc00147b8c0, 0xc0001e67e0)
        /go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:382 +0x1d3
created by github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).CheckTableData
        /go/pkg/mod/github.com/pingcap/tidb-tools@v4.0.1-0.20200612040216-6ddacc75561c+incompatible/pkg/diff/diff.go:260 +0x22a`

4. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

04f1c034ba43ea463e4242f5fdd2adffc0a19c52

**Comment by WangXiangUSTC** [comment]
fixed in https://github.com/pingcap/tidb-tools/pull/374
